name = "redisflare"
main = "./worker.ts"
compatibility_date = "2023-05-18"

# KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
	binding = "STORAGE"
	# replace this with your id
	id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	# replace this with your id
	preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Auth token for this redisflare instance
[vars]
	# replace this with your token
	AUTHTOKEN = "test123"
